import Foundation

/// The app-side extension of a Supabase Auth user, mirroring the `profiles` table.
struct Profile: Identifiable, Hashable, Codable, Sendable {
    let id: UUID
    var displayName: String
    /// Short shareable code other users type or scan to add you. Generated by Postgres.
    let friendCode: String
    var avatarURL: String?

    enum CodingKeys: String, CodingKey {
        case id
        case displayName = "display_name"
        case friendCode = "friend_code"
        case avatarURL = "avatar_url"
    }
}
